#!/usr/bin/env bash

set -euo pipefail

VLLM_CLAUDE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VLLM_CLAUDE_RUNTIME_DIR="${VLLM_CLAUDE_RUNTIME_DIR:-${VLLM_CLAUDE_DIR}/runtime}"
VLLM_CLAUDE_DATA_DIR="${VLLM_CLAUDE_DATA_DIR:-${VLLM_CLAUDE_RUNTIME_DIR}/data}"
VLLM_CLAUDE_LOG_DIR="${VLLM_CLAUDE_LOG_DIR:-${VLLM_CLAUDE_RUNTIME_DIR}/logs}"
VLLM_CLAUDE_RUN_DIR="${VLLM_CLAUDE_RUN_DIR:-${VLLM_CLAUDE_RUNTIME_DIR}/run}"

mkdir -p "${VLLM_CLAUDE_DATA_DIR}" "${VLLM_CLAUDE_LOG_DIR}" "${VLLM_CLAUDE_RUN_DIR}"
